sudo: required
services: 
  - docker

before_install:
  - docker build -t ra-cloud/dr -f Dockerfile.dev .

script:
  - docker run -e CI=true ra-cloud/dr npm run test

deploy:
  provider: $ONE_PROVIDER
  region: $ONE_REGION
  app: $ONE_APP
  env: $ONE_ENV
  bucket_name: $ONE_BUCKET_NAME
  bucket_path: $ONE_BUCKET_PATH
  on:
    branch: master
  access_key_id: $ONE_ACCESS_KEY
  secret_access_key: 
    secure: "$ONE_SECRET_KEY"
