sudo: required
services: 
  - docker

before_install:
  - docker build -t ra-cloud/dr -f Dockerfile.dev .

script:
  - docker run -e CI=true ra-cloud/dr npm run test

deploy:
  provider: \$01_PROVIDER
  region: '$01_REGION'
  app: "docker"
  env: "Docker-env"
  bucket_name: "$01_BUCKET_NAME"
  bucket_path: "$01_BUCKET_PATH"
  on:
    branch: master
  access_key_id: $01_ACCESS_KEY
  secret_access_key: 
    secure: "$01_SECRET_KEY"
